package com.wawey.parser;

public enum Rule {
    LITERAL,
    NUMBER_LITERAL,
    STRING_LITERAL,
    TYPE,
    NUMBER_TYPE,
    STRING_TYPE,
    IDENTIFIER,
    PRIMARY_EXPRESSION,
    ADDITIVE_EXPRESSION,
    SUM_EXPRESSION,
    SUBTRACT_EXPRESSION,
    MULTIPLICATIVE_EXPRESSION,
    MULTIPLY_EXPRESSION,
    DIVIDE_EXPRESSION,
    INITIALIZER,
    TYPE_ANNOTATION,
    VARIABLE_DECLARATION,
    PRINT_STATEMENT,
    COVER_INITIALIZED_NAME,
    STATEMENT,
    LINE,
    PROGRAM,
    FILE
}
